# -*- coding: utf-8 -*-
"""bunga_majemuk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qEm93i3pN8ZIppu1EdrMN5KF6Kisbmn
"""

# Instal Streamlit dan pyngrok
!pip install streamlit pyngrok --quiet

# Menggunakan perintah `mkdir -p` untuk memastikan direktori ada
!mkdir -p bunga_majemuk_app

# Nama file aplikasi Streamlit
app_file_name = "bunga_majemuk_app/app.py"

# Tulis kode Streamlit ke dalam file
kode_streamlit = """
import streamlit as st
import time # Untuk simulasi animasi loading

st.set_page_config(
    page_title="Kalkulator Bunga Majemuk Interaktif",
    page_icon="📈"
)

st.title("💰 Kalkulator Bunga Majemuk Interaktif")
st.markdown(\"\"\"
    Hitung pertumbuhan investasi Anda seiring waktu dengan efek compounding!
    Formula Bunga Majemuk: $A = P (1 + r/n)^{nt}$
    Dimana:
    - $A$ = Jumlah masa depan investasi/pinjaman, termasuk bunga
    - $P$ = Pokok investasi awal
    - $r$ = Tingkat bunga tahunan (dalam desimal)
    - $n$ = Jumlah kali bunga diterapkan per tahun
    - $t$ = Jumlah tahun uang diinvestasikan atau dipinjam
\"\"\")

st.sidebar.header("Pengaturan Investasi")

# Input dari pengguna
pokok = st.sidebar.number_input("Pokok Investasi Awal (P)", min_value=0.0, value=10000000.0, step=100000.0, format="%.2f")
tingkat_bunga = st.sidebar.slider("Tingkat Bunga Tahunan (r, %)", min_value=0.0, max_value=20.0, value=5.0, step=0.1) / 100
jumlah_tahun = st.sidebar.slider("Jangka Waktu (t, Tahun)", min_value=1, max_value=50, value=10, step=1)
frekuensi_kompon_opsi = st.sidebar.selectbox(
    "Frekuensi Kompon (n)",
    options=["Tahunan", "Semi-Tahunan", "Kuartalan", "Bulanan", "Harian"]
)

# Mengonversi frekuensi kompon ke nilai 'n'
if frekuensi_kompon_opsi == "Tahunan":
    n = 1
elif frekuensi_kompon_opsi == "Semi-Tahunan":
    n = 2
elif frekuensi_kompon_opsi == "Kuartalan":
    n = 4
elif frekuensi_kompon_opsi == "Bulanan":
    n = 12
elif frekuensi_kompon_opsi == "Harian":
    n = 365 # Mengabaikan tahun kabisat untuk penyederhanaan

st.sidebar.info(f"Bunga dikompon: {frekuensi_kompon_opsi}")

# Tombol untuk memulai perhitungan
if st.button("Hitung Bunga Majemuk"):
    if pokok <= 0:
        st.error("Pokok investasi awal harus lebih besar dari nol.")
    else:
        st.subheader("Memulai Perhitungan...")
        progress_bar = st.progress(0)
        status_text = st.empty()

        for percent_complete in range(101):
            time.sleep(0.01) # Simulasi waktu perhitungan
            progress_bar.progress(percent_complete)
            status_text.text(f"Progress: {percent_complete}%")

        status_text.success("Perhitungan Selesai!")
        st.balloons() # Animasi balon saat selesai

        # Hitung bunga majemuk
        jumlah_akhir = pokok * (1 + tingkat_bunga / n) ** (n * jumlah_tahun)
        bunga_dihasilkan = jumlah_akhir - pokok

        st.subheader("Hasil Perhitungan:")
        st.write(f"**Pokok Investasi Awal:** Rp {pokok:,.2f}")
        st.write(f"**Tingkat Bunga Tahunan:** {tingkat_bunga*100:.2f}%")
        st.write(f"**Jangka Waktu:** {jumlah_tahun} tahun")
        st.write(f"**Frekuensi Kompon:** {frekuensi_kompon_opsi} ({n} kali per tahun)")
        st.markdown(f"### **Jumlah Akhir Investasi:** Rp {jumlah_akhir:,.2f}")
        st.markdown(f"#### **Total Bunga yang Dihasilkan:** Rp {bunga_dihasilkan:,.2f}")

        st.markdown("---")
        st.info("Ingat, simulasi ini adalah perkiraan dan tidak menjamin hasil investasi yang sebenarnya.")

st.markdown("---")
st.write("Dibuat dengan ❤️ oleh program Python")
"""

with open(app_file_name, "w") as f:
    f.write(kode_streamlit)

print(f"Kode Streamlit telah disimpan ke {app_file_name}")

# Pastikan Anda telah mengganti 'YOUR_AUTH_TOKEN' dengan token ngrok Anda yang sebenarnya.
# Anda bisa mendapatkannya dari https://dashboard.ngrok.com/get-started/your-authtoken
!ngrok config add-authtoken 2xzHjWjbPUYqBgRJMNfhHfAZjG5_2PQT5khKCZRZU8GPP76cY

# Membunuh proses Streamlit yang mungkin masih berjalan sebelumnya
!pkill -f streamlit
